/*
 * THIS FILE WAS AUTOGENERATED BY CANOGEN.
 * MODIFICATIONS WILL BE LOST IF YOU RUN CANOGEN AGAIN.
 */
#ifndef CANOPY_BOILERPLATE_INCLUDED
#define CANOPY_BOILERPLATE_INCLUDED

#include <canopy.h>
#include <stdbool.h>

#define CANOPY_CLOUD_HOST "sandbox.canopy.link"
#define CANOPY_CLOUD_PORT 8080
#define CANOPY_CLOUD_USERNAME "myusername"
#define CANOPY_CLOUD_PASSWORD "mypassword"

static bool on_canopy_init(CanopyContext canopy);
static bool on_canopy_shutdown(CanopyContext canopy);
static bool on_connected(CanopyContext canopy);
static bool on_disconnected(CanopyContext canopy);
static bool on_report_requested(CanopyContext canopy);
static void dispatch(CanopyEventDetails event);


#define SDDL_FILENAME "/home/pi/canopy/canopy-embedded/examples/fan/fan.sddl"
#define SDDL_CLASSNAME "canopy.example.fan"
static bool on_change__speed(CanopyContext canopy, int8_t value);
static void dispatch(CanopyEventDetails event)
{
    CanopyContext ctx = canopy_event_context(event);
    if (canopy_event_control_name_matches(event, "speed"))
    {
        int8_t val;
        canopy_event_get_control_value_i8(event, &val);
        on_change__speed(ctx, val);
    }
}


static bool handle_canopy_event(CanopyContext ctx, CanopyEventDetails event)
{
    switch (canopy_get_event_type(event))
    {
        case CANOPY_EVENT_CONNECTION_ESTABLISHED:
        {
            on_connected(ctx);
            break;
        }
        case CANOPY_EVENT_CONNECTION_LOST:
        {
            on_disconnected(ctx);
            break;
        }
        case CANOPY_EVENT_REPORT_REQUESTED:
        {
            on_report_requested(ctx);
            break;
        }
        case CANOPY_EVENT_CONTROL_TRIGGER:
        {
            printf("dispatching!\n");
            dispatch(event);
        }
        default:
        {
            break;
        }
    }
    return true;
}

int main(int argc, const char *argv[])
{
    CanopyContext ctx;
    if (argc < 2)
    {
        printf("USAGE: %s <DEVICE_ID>\n", argv[0]);
        return -1;
    }
    ctx = canopy_init();
    on_canopy_init(ctx);
    canopy_load_sddl(ctx, SDDL_FILENAME, SDDL_CLASSNAME);

    canopy_register_event_callback(ctx, handle_canopy_event, NULL);

    canopy_set_cloud_host(ctx, CANOPY_CLOUD_HOST);
    canopy_set_cloud_port(ctx, CANOPY_CLOUD_PORT);
    canopy_set_cloud_username(ctx, CANOPY_CLOUD_USERNAME);
    canopy_set_cloud_password(ctx, CANOPY_CLOUD_PASSWORD);
    canopy_set_device_id(ctx, argv[1]);
    canopy_set_auto_reconnect(ctx, true);
    canopy_connect(ctx);

    canopy_event_loop(ctx);
    on_canopy_shutdown(ctx);
    canopy_shutdown(ctx);
    return 0;
}

#endif

