/*
 * THIS FILE WAS AUTOGENERATED BY CANOGEN.
 * MODIFICATIONS WILL BE LOST IF YOU RUN CANOGEN AGAIN.
 */
#ifndef CANOPY_BOILERPLATE_INCLUDED
#define CANOPY_BOILERPLATE_INCLUDED

#include <canopy.h>
#include <stdbool.h>

#define CANOPY_CLOUD_HOST "sandbox.canopy.link"
#define CANOPY_CLOUD_PORT 8080
#define CANOPY_CLOUD_USERNAME "myusername"
#define CANOPY_CLOUD_PASSWORD "mypassword"

static bool on_canopy_init();
static bool on_canopy_shutdown();
static bool on_connected();
static bool on_disconnected();
static bool on_report_requested();
static void dispatch(CanopyEventDetails event);

