all:
	gcc -I../../include -I../../3rdparty/libred/include -I../../3rdparty/libred/under_construction example_post_sample.c ../../src/canopy_simple.c ../../3rdparty/libred/src/red_string.c -Wall -Werror
