/*
 * THIS FILE WAS AUTOGENERATED BY CANOGEN.
 * MODIFICATIONS WILL BE LOST IF YOU RUN CANOGEN AGAIN.
 */
#ifndef CANOPY_BOILERPLATE_INCLUDED
#define CANOPY_BOILERPLATE_INCLUDED

#include <canopy.h>
#include <stdbool.h>

#define CANOPY_CLOUD_HOST "sandbox.canopy.link"
#define CANOPY_CLOUD_PORT 8080

static bool on_canopy_init(CanopyContext canopy);
static bool on_canopy_shutdown(CanopyContext canopy);
static bool on_connected(CanopyContext canopy);
static bool on_disconnected(CanopyContext canopy);
static bool on_report_requested(CanopyContext canopy);
static void dispatch(CanopyEventDetails event);

